# Generated by Django 2.2.1 on 2019-08-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='filename')),
            ],
            options={
                'verbose_name': 'ファイル名/File Name',
                'verbose_name_plural': 'ファイル名/File Name',
            },
        ),
    ]
