# Generated by Django 2.2.1 on 2019-08-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtdataconverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='filename'),
        ),
    ]
