# Generated by Django 2.2.1 on 2019-08-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtdataconverter', '0002_auto_20190827_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'verbose_name': 'ファイル/File', 'verbose_name_plural': 'ファイル/File'},
        ),
        migrations.AddField(
            model_name='datafile',
            name='text',
            field=models.TextField(blank=True, verbose_name='file text'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='file name'),
        ),
    ]
