# Generated by Django 2.2.1 on 2019-08-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtdataconverter', '0003_auto_20190827_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='text2',
            field=models.TextField(blank=True, verbose_name='file text'),
        ),
    ]
