# Generated by Django 2.2.1 on 2019-09-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtdataconverter', '0006_datafile_dragfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='dragfiles',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='text',
        ),
        migrations.AddField(
            model_name='datafile',
            name='dragaera',
            field=models.TextField(blank=True, verbose_name='convert files'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='upfile',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
