# Generated by Django 2.2.1 on 2019-09-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smtdataconverter', '0007_auto_20190904_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='dragaera',
            new_name='dragarea',
        ),
    ]
