# Generated by Django 2.2.1 on 2019-09-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtdataconverter', '0008_auto_20190904_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='upfile',
            field=models.FileField(upload_to='', verbose_name='upload file'),
        ),
    ]
