# Generated by Django 2.2.1 on 2019-09-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtdataconverter', '0009_auto_20190904_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='upfile',
            field=models.FileField(upload_to='test/', verbose_name='upload file'),
        ),
    ]
