# Generated by Django 2.2.1 on 2019-08-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membershiplicense',
            field=models.BooleanField(default=False, help_text='会員ライセンスの本体', verbose_name='メインライセンス/Membership License'),
        ),
    ]
