# Generated by Django 2.2.1 on 2019-09-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190827_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('upfile', models.FileField(upload_to='test/', verbose_name='upload file')),
            ],
            options={
                'verbose_name': 'ファイル/File',
                'verbose_name_plural': 'ファイル/File',
            },
        ),
    ]
