"""
Django settings for apptest20190917 project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4g^z-%kuo%iaqiide&0c2@yy!6t+pq+##7@b+i+5@wayd!)#yj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 20190916 本番用に'.pythonanywhere.com'を追加
ALLOWED_HOSTS = ['127.0.0.1', '.pythonanywhere.com']
#ALLOWED_HOSTS = []

# Application definition
#20190723　CustomUser用の設定
#accountはアプリの名前を設定する
AUTH_USER_MODEL = 'accounts.User'

#20190723　CustomUser用の設定
#ログイン用の画面関連
#'アプリ名:ページhtmlファイル名'　で指定する
LOGIN_URL = 'accounts:top'
LOGIN_REDIRECT_URL = 'onlinetop:membership_top'
LOGOUT_REDIRECT_URL = 'onlinetop:online_top'

#ブラウザを終了させた場合にログアウトさせる=セッションを削除する
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# メールをコンソールに表示する
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #以降　新規アプリ
    'accounts.apps.AccountsConfig',                     #20190723　CustomUser作成用のアプリ。appsはファイル名。
    'bootstrap4',                                       #20190723　bootstrap4アプリ。pip でのinstall必要。Djangoじゃなくていいらしい。 
    'widget_tweaks',                                    #20190723　widget_tweaksアプリ。bootstrap4とセット。
    'smtdataconverter.apps.SmtdataconverterConfig',     #20190807  smtdataconverter
    'onlinetop.apps.OnlinetopConfig',    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apptest20190917.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #20190806　真っ先に参照するtemplatesフォルダの場所
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),     #変更箇所　htmlの置き場所　templatesが基本 BASE_DIR+templatesフォルダを設定する
        ],
        'APP_DIRS': True,       #上の'DIRS'で見つからない場合に見に行くフォルダ。必ずTrueに。
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static', #20190723 おまじない？　とりあえず入れとく
            ],
        },
    },
]

WSGI_APPLICATION = 'apptest20190917.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ja'        #変更箇所　使用言語

TIME_ZONE = 'Asia/Tokyo'    #変更箇所　タイムゾーン

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

#20190723　静的ファイルへのアクセス設定
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

#20190917　mediaフォルダ
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

